//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDang
    {
        public BaiDang()
        {
            this.DanhSachYeuCaus = new HashSet<DanhSachYeuCau>();
        }
    
        public int IDBaiDang { get; set; }
        public string TenBaiDang { get; set; }
        public string TinhTrang { get; set; }
        public string NoiDung { get; set; }
        public string LopHoc { get; set; }
        public Nullable<int> SoHocVien { get; set; }
        public Nullable<int> HocPhi { get; set; }
        public Nullable<System.DateTime> SoBuoi_Tuan { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int IDMon { get; set; }
        public Nullable<int> IDKhuVuc { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
    
        public virtual KhuVuc KhuVuc { get; set; }
        public virtual Mon Mon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<DanhSachYeuCau> DanhSachYeuCaus { get; set; }
    }
}
