//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachYeuCau
    {
        public int IDDSYC { get; set; }
        public Nullable<int> IDBaiDang { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string TenDSYC { get; set; }
        public Nullable<System.DateTime> NgayYC { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
    }
}
